# Generated by Django 2.2 on 2020-04-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='OrderProduct',
        ),
    ]
