# Generated by Django 2.2 on 2020-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200418_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'success'), ('D', 'danger'), ('W', 'warning')], max_length=1, null=True),
        ),
    ]
