# Generated by Django 2.2 on 2020-04-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descrption',
        ),
    ]
