# Generated by Django 3.0.5 on 2020-04-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200420_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.IntegerField(null=True),
        ),
    ]
