# Generated by Django 2.2 on 2020-04-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
