# Generated by Django 2.2.10 on 2020-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200426_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='orders_to_deliver',
            field=models.ManyToManyField(to='core.Order'),
        ),
    ]
