# Generated by Django 2.2.10 on 2020-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_deliveryman_orders_to_deliver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryman',
            old_name='orders_to_deliver',
            new_name='orders',
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='orders_delivered',
            field=models.IntegerField(default=0),
        ),
    ]
