# Generated by Django 2.2.10 on 2020-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200430_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='core.Order'),
        ),
    ]
