# Generated by Django 2.2.10 on 2020-04-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
