# Generated by Django 2.2.10 on 2020-05-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('number', models.CharField(max_length=70)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='orders',
            field=models.ManyToManyField(to='core.Order'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('C', 'Credit card'), ('P', 'PayPal')], max_length=1)),
                ('PayPal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('credit_card_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CreditCardInfo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Client')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment'),
        ),
    ]
