# Generated by Django 2.2.10 on 2020-05-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200502_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
