# Generated by Django 2.2.10 on 2020-05-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_order_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='core.Order'),
        ),
    ]
