# Generated by Django 2.2.10 on 2020-05-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200506_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_item_select',
        ),
        migrations.CreateModel(
            name='ProductClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_item_select', models.ManyToManyField(to='core.AdditionalItem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
    ]
