# Generated by Django 2.2.10 on 2020-05-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200506_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclient',
            name='additional_items',
            field=models.ManyToManyField(blank=True, null=True, to='core.AdditionalItem'),
        ),
    ]
