# Generated by Django 2.2.10 on 2020-05-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200506_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclient',
            name='additional_items',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_items',
            field=models.ManyToManyField(blank=True, null=True, to='core.AdditionalItem'),
        ),
    ]
