# Generated by Django 2.2.10 on 2020-05-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200506_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclient',
            name='additional_items',
            field=models.ManyToManyField(blank=True, null=True, to='core.AdditionalItem'),
        ),
    ]
