# Generated by Django 2.2.10 on 2020-05-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_productclient_additional_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
    ]
