# Generated by Django 2.2.10 on 2020-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_product_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='additional_items',
            field=models.ManyToManyField(blank=True, null=True, to='core.AdditionalItem'),
        ),
    ]
