# Generated by Django 2.2.10 on 2020-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_client_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Credit card'), ('P', 'PayPal'), ('S', 'site curency')], max_length=1),
        ),
    ]
