# Generated by Django 2.2.10 on 2020-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge_tag',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
