# Generated by Django 2.2.10 on 2020-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_order_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refunded',
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='http://127.0.0.1:8000/media/gallery/avataar.png', upload_to='gallery'),
        ),
    ]
